### ISSUE TITLE
X11iraf installation

### ISSUE THREAD

**Issue by astronomypicture** [iraf-community/x11iraf#44]
Hi,
This is the first time I try to install X11IRAF, I have no experience as a system manager. I am working on Linux Mint 20.2 and followed the recipe. However, something is wrong. Here is the output I got:
 
$ make
make -C xgterm
make[1]: Entering directory '/home/andres/IRAF/x11iraf-2.1/xgterm'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/andres/IRAF/x11iraf-2.1/xgterm'
make -C ximtool
make[1]: Entering directory '/home/andres/IRAF/x11iraf-2.1/ximtool'
cd clients && mkpkg || true
Warning, hlib$mkpkg.inc line 5: macro `IRAFARCH' not found
warning: library `libpkg.a' not found
xc -c -w idxstr.x ism.x wcsgfterm.x
idxstr.c:13:10: fatal error: f2c.h: No such file or directory
   13 | #include "f2c.h"
      |          ^~~~~~~
compilation terminated.
ar r /home/andres/IRAF/x11iraf-2.1/ximtool/clients/libpkg.a idxstr.o ism.o wcsgfterm.o
ar: creating /home/andres/IRAF/x11iraf-2.1/ximtool/clients/libpkg.a
ar: idxstr.o: No such file or directory
xc -c -w t_wcspix.x wcimage.x wcmef.x wcmspec.x wcunknown.x
t_wcspix.c:13:10: fatal error: f2c.h: No such file or directory
   13 | #include "f2c.h"
      |          ^~~~~~~
compilation terminated.
ar r /home/andres/IRAF/x11iraf-2.1/ximtool/clients/libpkg.a t_wcspix.o wcimage.o wcmef.o wcmspec.o wcunknown.o
ar: creating /home/andres/IRAF/x11iraf-2.1/ximtool/clients/libpkg.a
ar: t_wcspix.o: No such file or directory
ranlib libpkg.a
ranlib: 'libpkg.a': No such file
Updated 8 files in libpkg.a
Warning, mkpkg line 13: module `libpkg.a' not found or returned error
xc -c -w x_ism.x
x_ism.c:13:10: fatal error: f2c.h: No such file or directory
   13 | #include "f2c.h"
      |          ^~~~~~~
compilation terminated.
xc -Nz   -z x_ism.o libpkg.a -o ism_wcspix.e -lds -lxtools -liminterp -lslalib
Warning: file `x_ism.o' not found
Warning: file `libpkg.a' not found
make[1]: Leaving directory '/home/andres/IRAF/x11iraf-2.1/ximtool'

**Comment by olebole** [comment]
You probably have IRAF already installed from Mint, right? Then you should set the environment variable `iraf`:
```shell
export iraf=/usr/lib/iraf/
```
(make sure you put a trailing slach `/`).

**Comment by olebole** [comment]
This looks like if you have different IRAF versions mixed somehow; maybe one self-compiled and one installed with apt.
In this case you must make sure that all environment variables are set OK, and that the "xc" executable is the one that matches the installation you want to use.
Specifically, the one that comes with the system doesn't link to `libcfitsio.a`, but to the dynamic library, so you probably use a different one.
However, the failure is related to the build of ximtool and there is just important to display world coordinates on the display (instead of pixel coordinates). In case you don't need the display of world coordinates or if you only want xgterm (and use f.e. ds9 for display), you can ignore this problem.

Finally, I really recommend **not** to start with IRAF anymore. IRAF is an old, abandoned system with no future. Instead, have a look at [Astropy](https://astropy.org) and its affiliated packages. They already good to replace most of the tasks IRAF did before and is evolving quickly. IRAF is a dead eand.
